# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# For Using Real Time Messaging API
gem 'eventmachine'
gem 'faye-websocket'
gem 'http'

# 一部のみ利用
gem 'slack-api'
gem 'faraday'